export const SET_USER_SESSION = "SET_USER_SESSION";
export const SET_DATA_USERS = "SET_DATA_USERS";
export const SET_DATA_USERS_PAGE = "SET_DATA_USERS_PAGE";
export const SET_DATA_MORE_USERS = "SET_DATA_MORE_USERS";
